# Generated by Django 6.0.4 on 2026-04-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_rename_users_to_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="notes",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="notes",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="notes.tag"
            ),
        ),
    ]
